name: Zeta Protocol

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Modules
        run: npm install

      - name: Execute Core
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          AFTERSHIP_API_KEY: ${{ secrets.AFTERSHIP_API_KEY }}
        run: node gammaCore.js
